# Put database information here #
db_host_mysql: localhost
db_port_mysql: 3306
db_data_base_name_mysql: app_hemofilia 
db_user_mysql: root
db_pass_mysql: marcos1985
############################################

## Secret to Jwt make the token

jwt_secret: app_hemofilia

api:
 hemofilia:
  secret: ${jwt_secret:app_hemofilia}
################################


host: ${db_host_mysql}
port: ${db_port_mysql}
database: ${db_data_base_name_mysql}
user: ${db_user_mysql}
pass: ${db_pass_mysql}


server:
 port: 8082
 
spring:
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useSSL=false&serverTimezone=UTC
    username: ${user}
    password: ${pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
