# Put database information here #
#db_host: localhost
#db_port: 3306
#db_data_base_name: app_hemofilia 
#db_user: root
#db_pass: marcos1985
############################################

## Secret to Jwt make the token

#jwt_secret: app_hemofilia

api:
 hemofilia:
  secret: ${jwt_secret:app_hemofilia}
################################


host: ${db_host}
port: ${db_port}
database: ${db_data_base_name}
user: ${db_user}
pass: ${db_pass}


#server:
# port: 8082
 
spring:
  datasource:
    url: jdbc:mysql://${host}:${port}/${database}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${user}
    password: ${pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
